--- #YAML:1.0
name:               Gtk2-SourceView2
version:            0.09
abstract:           Enhanced source code editor widget 
author:
    - Emmanuel Rodriguez <potyl@cpan.org>
license:            perl, gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Gtk2:  1.160
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
repository:         http://github.com/potyl/gtk2-sourceview2
